### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by henriquemnr** [DevelopersRede/magento1#1]
Bom dia, onde consigo o manual de configuração do módulo?

**Comment by netojoaobatista** [comment]
@henriquemnr, não há muito mistério para configurar o módulo:

O primeiro passo é acessar seu admin e ir até `Configuration` / `Payment Methods`. Feito isso, você encontrará a aba `e.Rede`; ela se parecerá com o seguinte:
![captura de tela de 2018-09-21 22-22-25](https://user-images.githubusercontent.com/273586/45911670-db102500-bdec-11e8-8865-1d95ddd3334a.png).

Aí os campos são:

1. **Enabled** - coloque como Yes
2. **Environment** - coloque como `Production` se já estiver indo para produção, ou `Test` se ainda estiver testando sua loja, homologando, etc.
3. **Affiliation** e **Token** - esses dois campos são do seu contrato com a Rede.
4. **Title** - é o nome do meio de pagamento que irá aparecer para o cliente da loja.
5. **Transaction Type** - tipo de transação que sua loja irá operar: você pode escolher `with automatic capture` para captura automática ou `with subsequent capture` para apenas autorizar e capturar depois.
6. ** Maximum number of installments** - para informar o número máximo de parcelas que deseja na sua loja
8. **Minimum amount for installment** - o valor mínimo do carrinho para habilitar o parcelamento.
9. ** Minimum installment amount** - para informar o valor mínimo de cada parcela. Esse campo é especialmente interessante, porque se a compra for de 100 e o valor mínimo por parcela for de 50, então o cliente só conseguirá parcelar em 2 vezes, mesmo que o máximo esteja configurado como 12.
10. **Soft Description** - é o nome que você quer que apareça na fatura do cartão do seu cliente.

**Comment by henriquemnr** [comment]
Obrigado!!!

outra pergunta, existe algum módulo para boleto via Erede?

Obrigado
Henrique Loureiro
Equipe Mão na Roda 4x4 | Escala Miniaturas
+55 11 9.8139-5281




Em sex, 21 de set de 2018 às 22:30, João Batista Neto <
notifications@github.com> escreveu:

**Comment by netojoaobatista** [comment]
Não. Nesse momento esse é o módulo para Magento 1.x.

:smile:

**Comment by henriquemnr** [comment]
Certo,

Só mais uma pergunta, ele é integrado com o sistema anti-fraude da Rede?


Henrique Loureiro
Equipe Mão na Roda 4x4 | Escala Miniaturas
+55 11 9.8139-5281




Em sex, 21 de set de 2018 às 22:35, João Batista Neto <
notifications@github.com> escreveu:

**Comment by netojoaobatista** [comment]
Sim e não ao mesmo tempo. Todo o backend do anti-fraude está implementado no módulo, mas ele está desativado. Como ainda está havendo uma análise de usabilidade e experiência do usuário, ele ainda está sendo validado; em breve a opção de habilitá-lo estará disponível na tela de configuração.

**Comment by henriquemnr** [comment]
@netojoaobatista fiquei com uma dúvida, o módulo parece estar instalado corretamente.

Estou testando ele em meu ambiente de testes. Fiz o cadastro como desenvolvedor e estou usando o token de testes.

Na hora de realizar o pedido, independente do cartão que coloco a transação não é autorizada.

Se coloco um cartão verdadeiro, o sistema fica processando infinitamente.
Se coloco um cartão de testes, o sistema simplesmente não fala nada.

Sabe me informar como posso testar o módulo?
