### ISSUE TITLE
Não Existe o arquivo

### ISSUE THREAD

**Issue by henriquemnr** [DevelopersRede/magento1#2]
O módulo está apresentando o seguinte erro:

2018-09-30T04:45:12+00:00 ERR (3): Warning: require_once(/dev/lib/erede-php/vendor/autoload.php): failed to open stream: No such file or directory  in /dev/app/code/community/Rede/Adquirencia/Model/Processor/Transacao.php on line 2

**Comment by netojoaobatista** [comment]
Chegou a instalar, @henriquemnr?

Em [instalação, no README.md](https://github.com/DevelopersRede/magento1#instala%C3%A7%C3%A3o), você vai encontrar o seguinte:

> Uma vez clonado, é importante ir até o diretório do SDK e fazer um composer install:
> ```
> cd lib/erede-php
> composer install
> ```

Se não fizer o `composer install`, não vai rolar mesmo. A alternativa para não precisar fazer isso, é baixar o pacote, é ir em [Releases](https://github.com/DevelopersRede/magento1/releases) e baixar a última versão - não o fonte, mas o pacote completo - ele já tem o SDK dentro dele.

**Comment by henriquemnr** [comment]
Opa, esqueci de pedir para fechar o tópico, fiz a instalação em outra
pasta, por isso deu erro, já resolvi aqui e está rodando.

Peguei outro erro, mas vou efetuar mais testes, para ver se é do módulo ou
de outra coisa aqui.


Henrique Loureiro
Equipe Mão na Roda 4x4 | Escala Miniaturas
+55 11 9.8139-5281




Em dom, 30 de set de 2018 às 13:11, João Batista Neto <
notifications@github.com> escreveu:

**Comment by henriquemnr** [comment]
Tuso certo, após instalar corretamente o SDK
